version: '3'

services:
    landing:
      image: mcfatem/static-landing:latest
      container_name: landing
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      networks:
        - proxy
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./data:/data
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.landing.entrypoints=http"
        - "traefik.http.routers.landing.rule=Host(`static.grinnell.edu`) && PathPrefix(`/landing`)"
        - "traefik.http.routers.landing.middlewares=landing-stripprefix"
        - "traefik.http.middlewares.landing-stripprefix.stripprefix.prefixes=/landing"
        - "traefik.http.middlewares.landing-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.landing.middlewares=landing-https-redirect"
        - "traefik.http.routers.landing-secure.entrypoints=https"
        - "traefik.http.routers.landing-secure.rule=Host(`static.grinnell.edu`) && PathPrefix(`/landing`)"
        - "traefik.http.routers.landing-secure.middlewares=landing-stripprefix"
        - "traefik.http.routers.landing-secure.tls=true"
        - "traefik.http.routers.landing-secure.tls.certresolver=http"
        - "traefik.http.routers.landing-secure.service=landing"
#        - "traefik.http.services.landing.loadbalancer.server.port=9000"
        - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
